"""paper trading

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 22:21:30.700773
"""
from alembic import op
import sqlalchemy as sa
import tape.db


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars_m15',
    sa.Column('asset', sa.String(length=8), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('asset', 'ts')
    )
    op.create_table('paper_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('exit', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('entry_time', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('exit_time', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=8), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=True),
    sa.Column('net_bps', sa.Float(), nullable=True),
    sa.Column('net_spread', sa.Float(), nullable=True),
    sa.Column('lots', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('pnl_usd', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('recorded_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'day', name='uq_paper_day')
    )
    with op.batch_alter_table('paper_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_days_run_id'), ['run_id'], unique=False)

    op.create_table('paper_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('balance_start', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('risk_pct', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('contract_oz', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('lot_step', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('started_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('first_day', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stopped_at', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_processed_at', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_runs_account'), ['account'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_runs_account'))

    op.drop_table('paper_runs')
    with op.batch_alter_table('paper_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_days_run_id'))

    op.drop_table('paper_days')
    op.drop_table('bars_m15')
    # ### end Alembic commands ###
