"""paper plan alerts

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 22:38:37.400069
"""
from alembic import op
import sqlalchemy as sa
import tape.db


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=96), nullable=False),
    sa.Column('sent_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'day', 'target', name='uq_paper_alert_delivery')
    )
    with op.batch_alter_table('paper_alert_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_alert_deliveries_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('paper_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerts', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_runs', schema=None) as batch_op:
        batch_op.drop_column('alerts')

    with op.batch_alter_table('paper_alert_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_alert_deliveries_run_id'))

    op.drop_table('paper_alert_deliveries')
    # ### end Alembic commands ###
